name: AbilityItemsHCF
version: 0.0.1
api: 4.0.0
author: Leo
main: Leo\AbilityItems\Main

permissions:
  ability.command:
    description: AbilityItems
    default: op
  removenpc.ability:
    description: Use for remove entity
    default: op
