name: Ability
version: 0.0.1
api: 4.0.0
author: itoozh
main: itoozh\AbilityItems\Main

permissions:
  ability.command:
    description: by itoozh
    default: op
  removenpc.ability:
    description: Use for remove entity
    default: op
  pp.command:
    description: pp
    default: op